# Generated by Django 2.2.6 on 2019-10-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='dynasty_end_time',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dynasty',
            name='dynasty_start_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
