# Generated by Django 2.2.6 on 2019-10-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_history', '0002_auto_20191028_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='dynasty_king',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
