# Generated by Django 2.2.6 on 2019-10-28 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dc_history', '0003_dynasty_dynasty_king'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynasty',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
