# Generated by Django 2.2.6 on 2019-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_history', '0006_auto_20191028_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='dynasty_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
